---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    team: development
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: docker.io/dmnlfrkn/myapp:api
        name: backend
        ports:
        - containerPort: 5000
      imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    team: development
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: docker.io/dmnlfrkn/myapp:client
        name: frontend
        ports:
        - containerPort: 3000
      imagePullPolicy: Always
