apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-client
  labels:
    team: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: client
        image: dmnlfrkn/myapp:client
        ports:
        - containerPort: 3000

# kubectl apply ... dan sonra 
# kubectl port-forward deplyment/"deployment_adi" dış_pot:iç_port