apiVersion: v1

kind: Pod

metadata:
  name: client-pod
  labels:
    app: frontend
    team: developer

spec:
  containers:
  - name: mernstackclient
    image: dmnlfrkn/myapp:client
    ports:
      - containerPort: 3000