apiVersion: v1

kind: Pod

metadata:
  name: multicontainer_pod
  labels:
    app: frontend-backend
    team: developer

spec:
  containers:
  - name: mernstackclient
    image: dmnlfrkn/myapp:client
    ports:
      - containerPort: 3000
  - name: mernstackapi
    image: dmnlfrkn/myapp:api
    ports:
      - containerPort: 5000